### ISSUE TITLE
content not being run through default converter

### ISSUE THREAD

**Issue by davidjgonzalez** [rustygeldmacher/jekyll-contentblocks#17]
First of all; love this plugin!

One issue i noticed is that the example in the README does not run the sidebar output through the Markdown converter (im assuming the Markdown converter should be used since the content page is a .md). For me it renders raw (almost as is noconvert was called) and i get the * written to the HTML and its not converted to a UL.

I am running jekyll 3.1.1.

**Comment by rustygeldmacher** [comment]
Hi @davidjgonzalez, in another ticket (#16) it was unfortunately discovered that Jekyll 3.1.1 breaks the plugin. I'll try and find some time soon to fix it, but in the mean time as a workaround would you be able to try Jekyll 3.0.3? I hope that helps! Thanks, and I will update this ticket to let you know when I'm able to get a fix in there.

**Comment by darwin** [comment]
Before I discovered that the problem is in contentblocks tag implementation I did bisect on jekyll to pin-point breaking commit for my jekyll site.

The breakage was introduced somewhere in these commits:
https://github.com/jekyll/jekyll/compare/9676b775de2ff78ae5331537083ae3c9d31f138c...7d81c00b29f7e317566c0e79f7539ab04231befc

I suspect this one:
https://github.com/jekyll/jekyll/commit/7d81c00b29f7e317566c0e79f7539ab04231befc

Unfortunately I cannot test my site exactly, because the code is broken until introduction of write? few commits later:
https://github.com/jekyll/jekyll/commit/0a6f289ba5e7e59421194b4de36ec36ca6399574

Maybe @parkr could shed some light on our problem with contentblock breakage? Thanks.

**Comment by parkr** [comment]
I do not know enough about this plugin to know where things could be going wrong. I suspect that monkey-patching is going to introduce a problem here. I recommend the use of Hooks: http://jekyllrb.com/docs/plugins/#hooks

**Comment by rustygeldmacher** [comment]
@parkr -- thank you so much for the pointer to Hooks! I didn't realize that was a thing (looks like they were added in 3.0). I was able to use `pre_render` to set up content blocks, which means no monkey patching. Gotta love that!

@davidjgonzalez, @darwin -- I just released jekyll-contentblocks v1.2.0 which adds support for Jekyll 3.1. Please give it a try and let me know how it goes!
